name: Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    container: zephyrprojectrtos/ci:latest
    env:
      CMAKE_PREFIX_PATH: /opt/toolchains
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: example-application

      - name: Clone zephyr repository
        run: |
          git clone --depth 1 --branch v2.7.0 https://github.com/zephyrproject-rtos/zephyr.git /opt/zephyrproject/zephyr

      - name: Set ZEPHYR_BASE environment variable
        run: echo "ZEPHYR_BASE=/opt/zephyrproject/zephyr" >> $GITHUB_ENV

      - name: Initialize
        working-directory: example-application
        run: |
          west init -l .
          west update

      - name: Build firmware
        working-directory: example-application
        shell: bash
        run: |
          source ${{ env.ZEPHYR_BASE }}/zephyr-env.sh
          west build -b custom_plank --board-root ../boards app

      - name: Twister Tests
        working-directory: example-application
        run: |
          ${{ env.ZEPHYR_BASE }}/scripts/twister -G --board-root boards/ --testsuite-root ./tests/

      - name: Archive firmware
        uses: actions/upload-artifact@v2
        with:
          name: firmware
          path: example-application/build/zephyr/zephyr.*