name: Build and Test

on: [push, pull_request]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    container: zephyrprojectrtos/ci:latest
    env:
      CMAKE_PREFIX_PATH: /opt/toolchains

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: example-application

      - name: Initialize
        working-directory: example-application
        run: |
          west init -l .
          west update

      - name: Build firmware
        working-directory: example-application
        run: |
          west build -b custom_plank app

      - name: Install Ruby
        run: |
          sudo apt-get update
          sudo apt-get install -y ruby

      - name: Run tests with Twister
        working-directory: example-application
        run: |
          ../zephyr/scripts/twister -G --board-root boards/ --testsuite-root ./tests/

      - name: Display Twister JSON report
        run: cat /__w/unitTest/unitTest/example-application/twister-out/twister.json

      - name: Create check run for Twister report
        uses: peter-evans/create-check@v1.3.0
        with:
          name: Twister Test Results
          conclusion: success
          text: |
            ## Twister Test Results

            See the test report for more details.
          annotations_file: /__w/unitTest/unitTest/example-application/twister-out/twister_report.xml

      - name: Archive firmware
        uses: actions/upload-artifact@v2
        with:
          name: firmware
          path: example-application/build/zephyr/zephyr.*
