name: Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    container: zephyrprojectrtos/ci:latest
    env:
      CMAKE_PREFIX_PATH: /opt/toolchains
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: example-application

      - name: Initialize
        working-directory: example-application
        run: |
          west init -l .
          west update
      - name: Build firmware
        working-directory: example-application
        run: |
          west build -b custom_plank app
      
      - name: Install Ruby
        run: |
          sudo apt-get update
          sudo apt-get install -y ruby
      
      - name: Twister Tests
        working-directory: example-application
        run: |
          ../zephyr/scripts/twister -G --board-root boards/ --testsuite-root ./tests/
      
      - name: Display Twister JSON report
        run: cat /__w/unitTest/unitTest/example-application/twister-out/twister.json

      - name: Display Twister xunit report 1
        run: cat /__w/unitTest/unitTest/example-application/twister-out/twister.xml

      - name: Display Twister xunit report 2
        run: cat /__w/unitTest/unitTest/example-application/twister-out/twister_report.xml

      - name: Install Python
        run: |
          sudo apt-get update
          sudo apt-get install -y python3

      - name: Set execute permission for display_results.py
        run: chmod +x .github/workflows/display_results.py

      - name: Display test results in a readable format
        run: python3 .github/workflows/display_results.py /__w/unitTest/unitTest/example-application/twister-out/twister.json

      - name: Archive firmware
        uses: actions/upload-artifact@v2
        with:
          name: firmware
          path: example-application/build/zephyr/zephyr.*
