name: Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    container: zephyrprojectrtos/ci:latest
    env:
      CMAKE_PREFIX_PATH: /opt/toolchains
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: example-application

      - name: Initialize
        working-directory: example-application
        run: |
          west init -l .
          west update
      - name: Build firmware
        working-directory: example-application
        run: |
          west build -b custom_plank apps/app
      
      - name: Install Ruby
        run: |
          sudo apt-get update
          sudo apt-get install -y ruby
      
      - name: Twister Tests
        working-directory: example-application
        run: |
          ../zephyr/scripts/twister -G --board-root boards/ --testsuite-root ./tests/
      
      - name: Install Python
        run: |
          sudo apt-get update
          sudo apt-get install -y python3

      - name: Print working directory
        run: |
          pwd
    
      - name: Set up the environment
        run: |
          chmod +x /__w/unitTest/unitTest/example-application/scripts/display_result.py

      - name: Run display_results.py script
        run: |
         /__w/unitTest/unitTest/example-application/scripts/display_result.py  /__w/unitTest/unitTest/example-application/twister-out/twister.json

      - name: Archive firmware
        uses: actions/upload-artifact@v2
        with:
          name: firmware
          path: example-application/build/zephyr/zephyr.*
